name: Build

on: [push]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: nuget/setup-nuget@v2
        with:
          nuget-version: '6.x'

      - name: Insert Wrapper
        run: |
          wget https://github.com/demaconsulting/DotnetToolWrapper/releases/download/1.0.0/DotnetToolWrapper.zip
          unzip -o DotnetToolWrapper.zip -d pack/tools/net6.0/any

      - name: Insert VSWhere
        run: |
          wget https://github.com/microsoft/vswhere/releases/download/3.1.7/vswhere.exe -O pack/tools/net6.0/any/vswhere.exe

      - name: Create Dotnet Tool
        run: |
          cd pack
          nuget pack

      - name: Upload asset
        uses: actions/upload-artifact@v4
        with:
          name: VSWhereTool
          path: pack/*.nupkg
