name: Release

on:
  workflow_dispatch:
    inputs:
      wrapper:
        description: 'Wrapper version (1.0.0)'
        required: true
      vswhere:
        description: 'VSWhere version (3.1.7)'
        required: true
      version:
        description: 'Release version (3.1.7)'
        required: true
      publish:
        description: 'Publish Type'
        required: true
        default: 'publish'
        type: choice
        options:
        - none
        - release
        - publish

jobs:
  release:
  
    permissions:
      contents: write
      packages: write

    runs-on: ubuntu-22.04
    
    steps:
    
    - uses: actions/checkout@v4

    - name: Setup dotnet 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.x

    - uses: nuget/setup-nuget@v2
      with:
        nuget-version: latest

    - name: Insert Wrapper
      run: |
        wget https://github.com/demaconsulting/DotnetToolWrapper/releases/download/${{ github.event.inputs.wrapper }}/DotnetToolWrapper.zip
        unzip -o DotnetToolWrapper.zip -d pack/tools/net6.0/any

    - name: Insert VSWhere
      run: |
        wget https://github.com/microsoft/vswhere/releases/download/${{ github.event.inputs.vswhere }}/vswhere.exe -O pack/tools/net6.0/any/vswhere.exe

    - name: Create Dotnet Tool
      run: |
        cd pack
        nuget pack -Version ${{ github.event.inputs.version }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifacts-release
        path: |
          pack/*.nupkg

    - name: Create release
      if: ${{ inputs.publish == 'release' || inputs.publish == 'publish' }}
      uses: ncipollo/release-action@v1
      with:
        artifacts: pack/*.nupkg
        generateReleaseNotes: true
        tag: ${{ github.event.inputs.version }}

    - name: Publish to Nuget
      if: ${{ inputs.publish == 'publish' }}
      run: >
        dotnet nuget push
        pack/*.nupkg
        --source "https://api.nuget.org/v3/index.json"
        --api-key "${{ secrets.DEMACONSULTINGNUGETKEY }}"
